server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    name: mysqlDB
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #数据库基本配置
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springdemo
      username: root
      password: root
      #监控统计拦截的filters
      filter: stat
      #初始化大小
      initial-size: 1
      #最大连接数
      max-active: 20
      #最小连接数
      min-idle: 1
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.domain


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    com.example.demo.dao: debug







